<?php

/**
 * @file
 * Implements hook_theme().
 */

/**
 * Register template files.
 */
function reinfate_theme($existing, $type, $theme, $path) : array {
  return [
    'reinfate-page' => [
      'variables' => [
        'title' => NULL,
        'text' => NULL,
        'form' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function reinfate_form_reinfate_NewCatForm_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $form['#attached']['library'][] = 'reinfate/global-styling';
}
