<?php

/**
 * @file
 * Implements hook_theme().
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Register template files.
 */
function reinfate_theme($existing, $type, $theme, $path) : array {
  return [
    'reinfate-page' => [
      'variables' => [
        'title' => NULL,
        'text' => NULL,
        'form' => NULL,
        'cats' => NULL,
      ],
    ],
    'reinfate-cat-block' => [
      'variables' => [
        'cat_name' => NULL,
        'email' => NULL,
        'cat_picture' => NULL,
        'created' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function reinfate_form_reinfate_NewCatForm_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#attached']['library'][] = 'reinfate/global-styling';
}
